In [60]:
# pip install matplotlib
!pip install seaborn

Requirement already satisfied: seaborn in ./.venv/lib/python3.9/site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in ./.venv/lib/python3.9/site-packages (from seaborn) (2.0.2)
Requirement already satisfied: pandas>=1.2 in ./.venv/lib/python3.9/site-packages (from seaborn) (2.3.1)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in ./.venv/lib/python3.9/site-packages (from seaborn) (3.9.4)
Requirement already satisfied: cycler>=0.10 in ./.venv/lib/python3.9/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: kiwisolver>=1.3.1 in ./.venv/lib/python3.9/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.7)
Requirement already satisfied: contourpy>=1.0.1 in ./.venv/lib/python3.9/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in ./.venv/lib/python3.9/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.2.3)
Requirement already satisfied: pillow>=8 in ./.venv/lib/python3.9/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (11.3.0)
Requirement already satisfied: importlib-resources>=3.2.0 in ./.venv/lib/python3.9/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (6.5.2)
Requirement already satisfied: fonttools>=4.22.0 in ./.venv/lib/python3.9/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.59.0)
Requirement already satisfied: python-dateutil>=2.7 in ./.venv/lib/python3.9/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: packaging>=20.0 in ./.venv/lib/python3.9/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (25.0)
Requirement already satisfied: tzdata>=2022.7 in ./.venv/lib/python3.9/site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: pytz>=2020.1 in ./.venv/lib/python3.9/site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: zipp>=3.1.0 in ./.venv/lib/python3.9/site-packages (from importlib-resources>=3.2.0->matplotlib!=3.6.1,>=3.4->seaborn) (3.23.0)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.9/site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
WARNING: You are using pip version 22.0.4; however, version 25.2 is available.
You should consider upgrading via the '/home/kishore/Luxury-Housing-Bangalore/.venv/bin/python3 -m pip install --upgrade pip' command.

In [61]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer

warnings.filterwarnings("ignore")

# %matplotlib inline

In [62]:
import pandas as pd

df=pd.read_csv("Luxury_Housing_Bangalore.csv")

df_clean = df

df_clean

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
0,PROP000001,Sarjapur Road,Project_0,RMZ,4025.0,4bhk,12.750846039118798,Primary,NRI,2025-03-31,7.990091,5.462863,Launch,Broker,yes,9.212491,18,Loved the amenities!
1,PROP000002,Indiranagar,Project_1,Puravankara,5760.0,3Bhk,16.292151871065954,Primary,Other,2024-06-30,4.839024,NaN,Under construction,NRI Desk,no,7.723898,106,NaN
2,PROP000003,Bannerghatta Road,Project_2,Tata Housing,7707.0,4bhk,10.517724412961911,Primary,HNI,2023-12-31,8.131315,8.669227,Ready to move,Direct,yes,6.985493,113,Agent was not responsive.
3,PROP000004,bellary road,Project_3,Embassy,6192.0,3BHK,9.396367494232896,Primary,HNI,2024-03-31,7.501657,5.720246,Ready to move,Online,yes,6.100929,106,Excellent location!
4,PROP000005,Koramangala,Project_4,SNN Raj,7147.0,4Bhk,15.345392444511946,Secondary,HNI,2024-12-31,4.525216,8.609649,Under construction,Broker,no,5.312510,18,Too far from my office.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100995,PROP004730,BELLARY ROAD,Project_229,Embassy,8546.0,5Bhk+,11.33081004147843,Secondary,CXO,2024-12-31,8.552797,6.221131,Under construction,NRI Desk,no,7.511827,22,Will buy after possession.
100996,PROP059810,Bellary Road,Project_309,Brigade,3408.0,3bhk,10.829373158307602,Primary,CXO,2024-09-30,6.879269,9.783611,Ready to move,Direct,no,9.851849,26,Agent was not responsive.
100997,PROP065099,HENNUR ROAD,Project_98,RMZ,4691.0,4BHK,11.183303152058548,Primary,NRI,2023-12-31,6.753812,8.383013,Under construction,Broker,no,9.101604,44,Loved the amenities!
100998,PROP093022,rajajinagar,Project_21,Embassy,7435.0,3BHK,10.914156376035923,Secondary,Other,2024-06-30,4.437787,5.756247,Under construction,Broker,yes,8.588551,66,Excellent location!
100999,PROP023826,whitefield,Project_325,L&T Realty,3218.0,4bhk,₹13.27 Cr,Primary,Startup Founder,2023-12-31,7.760416,9.989290,Under construction,Direct,yes,9.917647,58,Loved the amenities!

In [63]:
df_clean.head()

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
0,PROP000001,Sarjapur Road,Project_0,RMZ,4025.0,4bhk,12.750846039118798,Primary,NRI,2025-03-31,7.990091,5.462863,Launch,Broker,yes,9.212491,18,Loved the amenities!
1,PROP000002,Indiranagar,Project_1,Puravankara,5760.0,3Bhk,16.292151871065954,Primary,Other,2024-06-30,4.839024,NaN,Under construction,NRI Desk,no,7.723898,106,NaN
2,PROP000003,Bannerghatta Road,Project_2,Tata Housing,7707.0,4bhk,10.517724412961911,Primary,HNI,2023-12-31,8.131315,8.669227,Ready to move,Direct,yes,6.985493,113,Agent was not responsive.
3,PROP000004,bellary road,Project_3,Embassy,6192.0,3BHK,9.396367494232896,Primary,HNI,2024-03-31,7.501657,5.720246,Ready to move,Online,yes,6.100929,106,Excellent location!
4,PROP000005,Koramangala,Project_4,SNN Raj,7147.0,4Bhk,15.345392444511946,Secondary,HNI,2024-12-31,4.525216,8.609649,Under construction,Broker,no,5.312510,18,Too far from my office.

In [64]:
df_clean.tail()

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
100995,PROP004730,BELLARY ROAD,Project_229,Embassy,8546.0,5Bhk+,11.33081004147843,Secondary,CXO,2024-12-31,8.552797,6.221131,Under construction,NRI Desk,no,7.511827,22,Will buy after possession.
100996,PROP059810,Bellary Road,Project_309,Brigade,3408.0,3bhk,10.829373158307602,Primary,CXO,2024-09-30,6.879269,9.783611,Ready to move,Direct,no,9.851849,26,Agent was not responsive.
100997,PROP065099,HENNUR ROAD,Project_98,RMZ,4691.0,4BHK,11.183303152058548,Primary,NRI,2023-12-31,6.753812,8.383013,Under construction,Broker,no,9.101604,44,Loved the amenities!
100998,PROP093022,rajajinagar,Project_21,Embassy,7435.0,3BHK,10.914156376035923,Secondary,Other,2024-06-30,4.437787,5.756247,Under construction,Broker,yes,8.588551,66,Excellent location!
100999,PROP023826,whitefield,Project_325,L&T Realty,3218.0,4bhk,₹13.27 Cr,Primary,Startup Founder,2023-12-31,7.760416,9.989290,Under construction,Direct,yes,9.917647,58,Loved the amenities!

In [65]:
df_clean.columns

Index(['Property_ID', 'Micro_Market', 'Project_Name', 'Developer_Name',
       'Unit_Size_Sqft', 'Configuration', 'Ticket_Price_Cr',
       'Transaction_Type', 'Buyer_Type', 'Purchase_Quarter',
       'Connectivity_Score', 'Amenity_Score', 'Possession_Status',
       'Sales_Channel', 'NRI_Buyer', 'Locality_Infra_Score',
       'Avg_Traffic_Time_Min', 'Buyer_Comments'],
      dtype='object')

In [66]:
df_clean.shape

(101000, 18)

In [67]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101000 entries, 0 to 100999
Data columns (total 18 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Property_ID           101000 non-null  object
 1   Micro_Market          101000 non-null  object
 2   Project_Name          101000 non-null  object
 3   Developer_Name        101000 non-null  object
 4   Unit_Size_Sqft        90954 non-null   float64
 5   Configuration         101000 non-null  object
 6   Ticket_Price_Cr       90981 non-null   object
 7   Transaction_Type      101000 non-null  object
 8   Buyer_Type            101000 non-null  object
 9   Purchase_Quarter      101000 non-null  object
 10  Connectivity_Score    101000 non-null  float64
 11  Amenity_Score         90910 non-null   float64
 12  Possession_Status     101000 non-null  object
 13  Sales_Channel         101000 non-null  object
 14  NRI_Buyer             101000 non-null  object
 15  Locality_Infra_Score  101000 non-null  float64
 16  Avg_Traffic_Time_Min  101000 non-null  int64
 17  Buyer_Comments        82713 non-null   object
dtypes: float64(4), int64(1), object(13)
memory usage: 13.9+ MB

In [68]:
df_clean.describe()

,Unit_Size_Sqft,Connectivity_Score,Amenity_Score,Locality_Infra_Score,Avg_Traffic_Time_Min
count,90954.000000,101000.000000,90910.000000,101000.000000,101000.000000
mean,5972.274765,6.992619,7.503663,7.498426,67.182921
std,1783.397836,1.731757,1.440758,1.443128,30.271611
min,-1.000000,4.000031,5.000224,5.000013,15.000000
25%,4477.250000,5.494526,6.260329,6.247954,41.000000
50%,5990.000000,6.985805,7.499123,7.495614,67.000000
75%,7497.000000,8.490000,8.752207,8.749824,93.000000
max,8999.000000,9.999970,9.999865,9.999956,119.000000

In [69]:
df_clean.isnull().sum()

Property_ID                 0
Micro_Market                0
Project_Name                0
Developer_Name              0
Unit_Size_Sqft          10046
Configuration               0
Ticket_Price_Cr         10019
Transaction_Type            0
Buyer_Type                  0
Purchase_Quarter            0
Connectivity_Score          0
Amenity_Score           10090
Possession_Status           0
Sales_Channel               0
NRI_Buyer                   0
Locality_Infra_Score        0
Avg_Traffic_Time_Min        0
Buyer_Comments          18287
dtype: int64

In [70]:
print("Before cleaning: ",df_clean['Ticket_Price_Cr'].dtype)

Before cleaning:  object

In [71]:
df_clean['Ticket_Price_Cr'] = df_clean['Ticket_Price_Cr'].astype(str)

df_clean['Ticket_Price_Cr'] = df_clean['Ticket_Price_Cr'].str.replace(r'[₹,]', '', regex=True)
df_clean['Ticket_Price_Cr'] = df_clean['Ticket_Price_Cr'].str.replace(r'\s*Cr\s*', '', regex=True)

df_clean['Ticket_Price_Cr'] = pd.to_numeric(df_clean['Ticket_Price_Cr'], errors='coerce')

median = df_clean['Ticket_Price_Cr'].median()
df_clean["Ticket_Price_Cr"] = df_clean['Ticket_Price_Cr'].fillna(median)

print("After cleaning: ",df_clean['Ticket_Price_Cr'].dtype)
df_clean['Ticket_Price_Cr']
df_clean

After cleaning:  float64

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
0,PROP000001,Sarjapur Road,Project_0,RMZ,4025.0,4bhk,12.750846,Primary,NRI,2025-03-31,7.990091,5.462863,Launch,Broker,yes,9.212491,18,Loved the amenities!
1,PROP000002,Indiranagar,Project_1,Puravankara,5760.0,3Bhk,16.292152,Primary,Other,2024-06-30,4.839024,NaN,Under construction,NRI Desk,no,7.723898,106,NaN
2,PROP000003,Bannerghatta Road,Project_2,Tata Housing,7707.0,4bhk,10.517724,Primary,HNI,2023-12-31,8.131315,8.669227,Ready to move,Direct,yes,6.985493,113,Agent was not responsive.
3,PROP000004,bellary road,Project_3,Embassy,6192.0,3BHK,9.396367,Primary,HNI,2024-03-31,7.501657,5.720246,Ready to move,Online,yes,6.100929,106,Excellent location!
4,PROP000005,Koramangala,Project_4,SNN Raj,7147.0,4Bhk,15.345392,Secondary,HNI,2024-12-31,4.525216,8.609649,Under construction,Broker,no,5.312510,18,Too far from my office.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100995,PROP004730,BELLARY ROAD,Project_229,Embassy,8546.0,5Bhk+,11.330810,Secondary,CXO,2024-12-31,8.552797,6.221131,Under construction,NRI Desk,no,7.511827,22,Will buy after possession.
100996,PROP059810,Bellary Road,Project_309,Brigade,3408.0,3bhk,10.829373,Primary,CXO,2024-09-30,6.879269,9.783611,Ready to move,Direct,no,9.851849,26,Agent was not responsive.
100997,PROP065099,HENNUR ROAD,Project_98,RMZ,4691.0,4BHK,11.183303,Primary,NRI,2023-12-31,6.753812,8.383013,Under construction,Broker,no,9.101604,44,Loved the amenities!
100998,PROP093022,rajajinagar,Project_21,Embassy,7435.0,3BHK,10.914156,Secondary,Other,2024-06-30,4.437787,5.756247,Under construction,Broker,yes,8.588551,66,Excellent location!
100999,PROP023826,whitefield,Project_325,L&T Realty,3218.0,4bhk,13.270000,Primary,Startup Founder,2023-12-31,7.760416,9.989290,Under construction,Direct,yes,9.917647,58,Loved the amenities!

In [72]:
median_am = df_clean['Amenity_Score'].median()
df_clean['Amenity_Score'] = df_clean['Amenity_Score'].fillna(median_am)
df_clean['Amenity_Score'].dtype

dtype('float64')

In [73]:
median_am = df_clean['Unit_Size_Sqft'].median()
df_clean['Unit_Size_Sqft'] = df_clean['Unit_Size_Sqft'].fillna(median_am)
df_clean['Unit_Size_Sqft'].dtype

dtype('float64')

In [74]:
df_clean['Purchase_Quarter'].unique()

array(['2025-03-31', '2024-06-30', '2023-12-31', '2024-03-31',
       '2024-12-31', '2023-09-30', '2024-09-30', '2023-06-30'],
      dtype=object)

In [75]:
df_clean['Purchase_Quarter'] = pd.to_datetime(df_clean['Purchase_Quarter'])
df_clean['Purchase_Quarter']

0        2025-03-31
1        2024-06-30
2        2023-12-31
3        2024-03-31
4        2024-12-31
            ...
100995   2024-12-31
100996   2024-09-30
100997   2023-12-31
100998   2024-06-30
100999   2023-12-31
Name: Purchase_Quarter, Length: 101000, dtype: datetime64[ns]

In [76]:

df_clean['Purchase_Day'] = df_clean['Purchase_Quarter'].dt.day
df_clean['Purchase_Month'] = df_clean['Purchase_Quarter'].dt.month
df_clean['Purchase_Year'] = df_clean['Purchase_Quarter'].dt.year
df_clean['Purchase_Quarter']

0        2025-03-31
1        2024-06-30
2        2023-12-31
3        2024-03-31
4        2024-12-31
            ...
100995   2024-12-31
100996   2024-09-30
100997   2023-12-31
100998   2024-06-30
100999   2023-12-31
Name: Purchase_Quarter, Length: 101000, dtype: datetime64[ns]

In [77]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101000 entries, 0 to 100999
Data columns (total 21 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Property_ID           101000 non-null  object
 1   Micro_Market          101000 non-null  object
 2   Project_Name          101000 non-null  object
 3   Developer_Name        101000 non-null  object
 4   Unit_Size_Sqft        101000 non-null  float64
 5   Configuration         101000 non-null  object
 6   Ticket_Price_Cr       101000 non-null  float64
 7   Transaction_Type      101000 non-null  object
 8   Buyer_Type            101000 non-null  object
 9   Purchase_Quarter      101000 non-null  datetime64[ns]
 10  Connectivity_Score    101000 non-null  float64
 11  Amenity_Score         101000 non-null  float64
 12  Possession_Status     101000 non-null  object
 13  Sales_Channel         101000 non-null  object
 14  NRI_Buyer             101000 non-null  object
 15  Locality_Infra_Score  101000 non-null  float64
 16  Avg_Traffic_Time_Min  101000 non-null  int64
 17  Buyer_Comments        82713 non-null   object
 18  Purchase_Day          101000 non-null  int32
 19  Purchase_Month        101000 non-null  int32
 20  Purchase_Year         101000 non-null  int32
dtypes: datetime64[ns](1), float64(5), int32(3), int64(1), object(11)
memory usage: 15.0+ MB

In [78]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101000 entries, 0 to 100999
Data columns (total 21 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Property_ID           101000 non-null  object
 1   Micro_Market          101000 non-null  object
 2   Project_Name          101000 non-null  object
 3   Developer_Name        101000 non-null  object
 4   Unit_Size_Sqft        101000 non-null  float64
 5   Configuration         101000 non-null  object
 6   Ticket_Price_Cr       101000 non-null  float64
 7   Transaction_Type      101000 non-null  object
 8   Buyer_Type            101000 non-null  object
 9   Purchase_Quarter      101000 non-null  datetime64[ns]
 10  Connectivity_Score    101000 non-null  float64
 11  Amenity_Score         101000 non-null  float64
 12  Possession_Status     101000 non-null  object
 13  Sales_Channel         101000 non-null  object
 14  NRI_Buyer             101000 non-null  object
 15  Locality_Infra_Score  101000 non-null  float64
 16  Avg_Traffic_Time_Min  101000 non-null  int64
 17  Buyer_Comments        82713 non-null   object
 18  Purchase_Day          101000 non-null  int32
 19  Purchase_Month        101000 non-null  int32
 20  Purchase_Year         101000 non-null  int32
dtypes: datetime64[ns](1), float64(5), int32(3), int64(1), object(11)
memory usage: 15.0+ MB

In [79]:
df_clean['Buyer_Comments'] = df_clean['Buyer_Comments'].fillna('No comments')
df_clean['Buyer_Comments'] = df_clean['Buyer_Comments'].str.strip()
df_clean['Buyer_Comments'] = df_clean['Buyer_Comments'].str.lower()
df_clean['Buyer_Comments']

0               loved the amenities!
1                        no comments
2          agent was not responsive.
3                excellent location!
4            too far from my office.
                     ...
100995    will buy after possession.
100996     agent was not responsive.
100997          loved the amenities!
100998           excellent location!
100999          loved the amenities!
Name: Buyer_Comments, Length: 101000, dtype: object

In [80]:
df_clean['Micro_Market'] = df_clean['Micro_Market'].str.lower()

# df_clean['Micro_Market']

df_clean['Developer_Name'] = df_clean['Developer_Name'].str.lower()

# df_clean['Developer_Name']

df_clean['Micro_Market'] = df_clean['Micro_Market'].str.strip()

# df_clean['Micro_Market']

df_clean['Developer_Name'] = df_clean['Developer_Name'].str.strip()

df_clean['Developer_Name']

0                  rmz
1          puravankara
2         tata housing
3              embassy
4              snn raj
              ...
100995         embassy
100996         brigade
100997             rmz
100998         embassy
100999      l&t realty
Name: Developer_Name, Length: 101000, dtype: object

In [81]:
df_clean['Price_per_Sqft'] = (df_clean['Ticket_Price_Cr'] * 1e7) / df_clean['Unit_Size_Sqft']
# df['Price_per_Sqft']

df_clean['Quarter_Number'] = df_clean['Purchase_Quarter'].dt.quarter
df_clean['Quarter_Number']

0         1
1         2
2         4
3         1
4         4
         ..
100995    4
100996    3
100997    4
100998    2
100999    4
Name: Quarter_Number, Length: 101000, dtype: int32

In [82]:
df_clean

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,...,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments,Purchase_Day,Purchase_Month,Purchase_Year,Price_per_Sqft,Quarter_Number
0,PROP000001,sarjapur road,Project_0,rmz,4025.0,4bhk,12.750846,Primary,NRI,2025-03-31,...,Broker,yes,9.212491,18,loved the amenities!,31,3,2025,31679.120594,1
1,PROP000002,indiranagar,Project_1,puravankara,5760.0,3Bhk,16.292152,Primary,Other,2024-06-30,...,NRI Desk,no,7.723898,106,no comments,30,6,2024,28284.985887,2
2,PROP000003,bannerghatta road,Project_2,tata housing,7707.0,4bhk,10.517724,Primary,HNI,2023-12-31,...,Direct,yes,6.985493,113,agent was not responsive.,31,12,2023,13646.976013,4
3,PROP000004,bellary road,Project_3,embassy,6192.0,3BHK,9.396367,Primary,HNI,2024-03-31,...,Online,yes,6.100929,106,excellent location!,31,3,2024,15175.012103,1
4,PROP000005,koramangala,Project_4,snn raj,7147.0,4Bhk,15.345392,Secondary,HNI,2024-12-31,...,Broker,no,5.312510,18,too far from my office.,31,12,2024,21471.096187,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100995,PROP004730,bellary road,Project_229,embassy,8546.0,5Bhk+,11.330810,Secondary,CXO,2024-12-31,...,NRI Desk,no,7.511827,22,will buy after possession.,31,12,2024,13258.612265,4
100996,PROP059810,bellary road,Project_309,brigade,3408.0,3bhk,10.829373,Primary,CXO,2024-09-30,...,Direct,no,9.851849,26,agent was not responsive.,30,9,2024,31776.329690,3
100997,PROP065099,hennur road,Project_98,rmz,4691.0,4BHK,11.183303,Primary,NRI,2023-12-31,...,Broker,no,9.101604,44,loved the amenities!,31,12,2023,23839.912923,4
100998,PROP093022,rajajinagar,Project_21,embassy,7435.0,3BHK,10.914156,Secondary,Other,2024-06-30,...,Broker,yes,8.588551,66,excellent location!,30,6,2024,14679.430230,2
100999,PROP023826,whitefield,Project_325,l&t realty,3218.0,4bhk,13.270000,Primary,Startup Founder,2023-12-31,...,Direct,yes,9.917647,58,loved the amenities!,31,12,2023,41236.793039,4

In [86]:
luxury_housing_db = df_clean
luxury_housing_db.isnull().sum()
luxury_housing_db.to_csv('Cleaned_CSV_File.csv', index=False)

In [85]:
import mysql.connector

connection = mysql.connector.connect(
    host = "localhost",
    user = "root",
    password = "kishore24",
    database = "luxury_housing"
)

cursor = connection.cursor()

def creation_of_table(cursor, table_name, df):
    dtype_map ={
        "int64": "int",
        "float64": "float",
        "object": "varchar(255)",
        "bool": "boolean",
        "datetime64[ns]": "datetime"

    }

    columns = []
    for cols in df.columns:
        dtype = str(df[cols].dtype)
        sql_type= dtype_map.get(dtype, "VARCHAR(255)")
        columns.append(f"`{cols}` {sql_type}")


    table_declaration = ", ".join(columns)
    query = f"CREATE TABLE `{table_name}` ({table_declaration});"

    cursor.execute(query)
    connection.commit()


def insertion_of_table(cursor, connection, df, table_name):
    col= ", ".join([f"`{cols}`" for cols in df.columns])
    placeholders = ", ".join(["%s"]* len(df.columns))
    query = f"INSERT INTO `{table_name}`({col}) VALUES ({placeholders});"

    rows = list(df.itertuples(index=False, name= None))
    cursor.executemany(query, rows)
    connection.commit()



table_name = "luxury_housing"
creation_of_table(cursor, table_name, luxury_housing_db)
insertion_of_table(cursor, connection, luxury_housing_db, table_name)
print(f"Inserted {len(luxury_housing_db)} rows into `{table_name}`")




cursor.close()
connection.close()

ProgrammingError: 1050 (42S01): Table 'luxury_housing' already exists

In [ ]:
numeric_cols = [feature for feature in df_clean.columns if df_clean[feature].dtype != 'O']
categorical_cols = [feature for feature in df_clean.columns if df_clean[feature].dtype == 'O']

In [ ]:
print(f'We have {len(numeric_cols)} of numeric features : {numeric_cols}')
print(f'We have {len(categorical_cols)} of numeric features : {categorical_cols}')

We have 12 of numeric features : ['Unit_Size_Sqft', 'Ticket_Price_Cr', 'Purchase_Quarter', 'Connectivity_Score', 'Amenity_Score', 'Locality_Infra_Score', 'Avg_Traffic_Time_Min', 'Purchase_Day', 'Purchase_Month', 'Purchase_Year', 'Price_per_Sqft', 'Quarter_Number']
We have 11 of numeric features : ['Property_ID', 'Micro_Market', 'Project_Name', 'Developer_Name', 'Configuration', 'Transaction_Type', 'Buyer_Type', 'Possession_Status', 'Sales_Channel', 'NRI_Buyer', 'Buyer_Comments']